/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'advayabha' at '11/2/16 1:50 AM' with Gradle 2.14.1
 *
 * @author advayabha, @date 11/2/16 1:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
